branch-defaults:
  master:
    environment: dashboard-env
    group_suffix: null
global:
  application_name: DashboardPrototype
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: sa-east-1
  profile: eb-cli
  repository: null
  sc: git
